# Data Preprocessing
:label:`sec_pandas`

So far, we have been working with synthetic data
that arrived in ready-made tensors.
However, to apply deep learning in the wild
we must extract messy data 
stored in arbitrary formats,
and preprocess it to suit our needs.
Fortunately, the *pandas* [library](https://pandas.pydata.org/) 
can do much of the heavy lifting.
This section, while no substitute 
for a proper *pandas* [tutorial](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html),
will give you a crash course
on some of the most common routines.

## Reading the Dataset

Comma-separated values (CSV) files are ubiquitous 
for the storing of tabular (spreadsheet-like) data.
In them, each line corresponds to one record
and consists of several (comma-separated) fields, e.g.,
"Albert Einstein,March 14 1879,Ulm,Federal polytechnic school,field of gravitational physics".
To demonstrate how to load CSV files with `pandas`, 
we (**create a CSV file below**) `../data/house_tiny.csv`. 
This file represents a dataset of homes,
where each row corresponds to a distinct home
and the columns correspond to the number of rooms (`NumRooms`),
the roof type (`RoofType`), and the price (`Price`).


In [1]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

Now let's import `pandas` and load the dataset with `read_csv`.


In [2]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


## Data Preparation

In supervised learning, we train models
to predict a designated *target* value,
given some set of *input* values. 
Our first step in processing the dataset
is to separate out columns corresponding
to input versus target values. 
We can select columns either by name or
via integer-location based indexing (`iloc`).

You might have noticed that `pandas` replaced
all CSV entries with value `NA`
with a special `NaN` (*not a number*) value. 
This can also happen whenever an entry is empty,
e.g., "3,,,270000".
These are called *missing values* 
and they are the "bed bugs" of data science,
a persistent menace that you will confront
throughout your career. 
Depending upon the context, 
missing values might be handled
either via *imputation* or *deletion*.
Imputation replaces missing values 
with estimates of their values
while deletion simply discards 
either those rows or those columns
that contain missing values. 

Here are some common imputation heuristics.
[**For categorical input fields, 
we can treat `NaN` as a category.**]
Since the `RoofType` column takes values `Slate` and `NaN`,
`pandas` can convert this column 
into two columns `RoofType_Slate` and `RoofType_nan`.
A row whose roof type is `Slate` will set values 
of `RoofType_Slate` and `RoofType_nan` to 1 and 0, respectively.
The converse holds for a row with a missing `RoofType` value.


In [3]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


For missing numerical values, 
one common heuristic is to 
[**replace the `NaN` entries with 
the mean value of the corresponding column**].


In [4]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


## Conversion to the Tensor Format

Now that [**all the entries in `inputs` and `targets` are numerical,
we can load them into a tensor**] (recall :numref:`sec_ndarray`).


In [5]:
import torch

X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

## Discussion

You now know how to partition data columns, 
impute missing variables, 
and load `pandas` data into tensors. 
In :numref:`sec_kaggle_house`, you will
pick up some more data processing skills. 
While this crash course kept things simple,
data processing can get hairy.
For example, rather than arriving in a single CSV file,
our dataset might be spread across multiple files
extracted from a relational database.
For instance, in an e-commerce application,
customer addresses might live in one table
and purchase data in another.
Moreover, practitioners face myriad data types
beyond categorical and numeric, for example,
text strings, images,
audio data, and point clouds. 
Oftentimes, advanced tools and efficient algorithms 
are required in order to prevent data processing from becoming
the biggest bottleneck in the machine learning pipeline. 
These problems will arise when we get to 
computer vision and natural language processing. 
Finally, we must pay attention to data quality.
Real-world datasets are often plagued 
by outliers, faulty measurements from sensors, and recording errors, 
which must be addressed before 
feeding the data into any model. 
Data visualization tools such as [seaborn](https://seaborn.pydata.org/), 
[Bokeh](https://docs.bokeh.org/), or [matplotlib](https://matplotlib.org/)
can help you to manually inspect the data 
and develop intuitions about 
the type of problems you may need to address.


## Exercises

1. Try loading datasets, e.g., Abalone from the [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets.php) and inspect their properties. What fraction of them has missing values? What fraction of the variables is numerical, categorical, or text?
1. Try indexing and selecting data columns by name rather than by column number. The pandas documentation on [indexing](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html) has further details on how to do this.
1. How large a dataset do you think you could load this way? What might be the limitations? Hint: consider the time to read the data, representation, processing, and memory footprint. Try this out on your laptop. What happens if you try it out on a server? 
1. How would you deal with data that has a very large number of categories? What if the category labels are all unique? Should you include the latter?
1. What alternatives to pandas can you think of? How about [loading NumPy tensors from a file](https://numpy.org/doc/stable/reference/generated/numpy.load.html)? Check out [Pillow](https://python-pillow.org/), the Python Imaging Library.


In [46]:
airline = os.path.join('..', 'data', 'airline_review.csv')
data = pd.read_csv(airline)
print(data)

    Unnamed: 0 Type Of Traveller        Seat Type  \
0            0    Couple Leisure   Business Class   
1            1          Business    Economy Class   
2            2    Couple Leisure      First Class   
3            3          Business   Business Class   
4            4    Couple Leisure    Economy Class   
..         ...               ...              ...   
95          95    Couple Leisure    Economy Class   
96          96    Couple Leisure  Premium Economy   
97          97          Business    Economy Class   
98          98      Solo Leisure    Economy Class   
99          99      Solo Leisure   Business Class   

                                       Route      Date Flown  Seat Comfort  \
0                           Athens to London  September 2023             1   
1               Milan to San Jose via London  September 2023             3   
2           Dallas to Dubrovnik via Heathrow  September 2023             1   
3                          London to Seville  Septe

In [47]:
pre_data, post_data = data.iloc[:,:3], data.iloc[:,6:]
data = pd.concat([pre_data, post_data],axis=1)
data

Unnamed: 0 Type Of Traveller        Seat Type  Cabin Staff Service  \
0            0    Couple Leisure   Business Class                    1   
1            1          Business    Economy Class                    3   
2            2    Couple Leisure      First Class                    4   
3            3          Business   Business Class                    1   
4            4    Couple Leisure    Economy Class                    1   
..         ...               ...              ...                  ...   
95          95    Couple Leisure    Economy Class                    4   
96          96    Couple Leisure  Premium Economy                    4   
97          97          Business    Economy Class                    4   
98          98      Solo Leisure    Economy Class                    5   
99          99      Solo Leisure   Business Class                    5   

    Food and Beverages  Inflight Entertainment  Ground Service  \
0                    1                       1               1   
1                    2                       4               1   
2                    4                       3               3   
3                    1                       3               1   
4                    1                       3               2   
..                 ...                     ...             ...   
95                   5                       5               1   
96                   1                       3               5   
97                   4                       4               2   
98                   3                       3               5   
99                   4                       5               4   

    Value For Money Recommended  
0                 1          no  
1                 1          no  
2                 2          no  
3                 1          no  
4                 1          no  
..              ...         ...  
95                2          no  
96                1          no  
97                2          no  
98                4          no  
99                4         yes  

[100 rows x 9 columns]

In [51]:
ip, op = data.iloc[:,:8], data.iloc[:,8:]
ip, op

(    Unnamed: 0 Type Of Traveller        Seat Type  Cabin Staff Service  \
 0            0    Couple Leisure   Business Class                    1   
 1            1          Business    Economy Class                    3   
 2            2    Couple Leisure      First Class                    4   
 3            3          Business   Business Class                    1   
 4            4    Couple Leisure    Economy Class                    1   
 ..         ...               ...              ...                  ...   
 95          95    Couple Leisure    Economy Class                    4   
 96          96    Couple Leisure  Premium Economy                    4   
 97          97          Business    Economy Class                    4   
 98          98      Solo Leisure    Economy Class                    5   
 99          99      Solo Leisure   Business Class                    5   
 
     Food and Beverages  Inflight Entertainment  Ground Service  \
 0                    1        

In [53]:
ip = pd.get_dummies(ip, dummy_na=False)
op = pd.get_dummies(op, dummy_na=False)

In [54]:
x = torch.tensor(ip.to_numpy(dtype=float))
y = torch.tensor(op.to_numpy(dtype=float))
x,y

(tensor([[ 0.,  1.,  1.,  ...,  0.,  0.,  0.],
         [ 1.,  3.,  2.,  ...,  1.,  0.,  0.],
         [ 2.,  4.,  4.,  ...,  0.,  1.,  0.],
         ...,
         [97.,  4.,  4.,  ...,  1.,  0.,  0.],
         [98.,  5.,  3.,  ...,  1.,  0.,  0.],
         [99.,  5.,  4.,  ...,  0.,  0.,  0.]], dtype=torch.float64),
 tensor([[1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [0., 1.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [0., 1.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [0., 1.],
         [0., 1.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [1., 0.],
         [0., 1.],
         [1., 0.],
         [1., 0.

In [55]:
inputs["NumRooms"]

0    3.0
1    2.0
2    4.0
3    3.0
Name: NumRooms, dtype: float64

[Discussions](https://discuss.d2l.ai/t/29)
